apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: tpwkfy6in-nodejs 
  janus-idp.io/tekton: tpwkfy6in-nodejs
  backstage.io/kubernetes-id: tpwkfy6in-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tpwkfy6in-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml